interface Endpoints {
    login: string;
    me: string;
    logout: string;
    getUsers: string;
    getUserId: string;
    createUser: string;
    updateUser: string;
    deleteUser: string;
    getMedAll: string;
    getGroupedMedAll: string;
    getMedExp: string;
    getMedId: string;
    createMed: string;
    updateMed: string;
    deleteMed: string;
    createTransac: string;
    getTransacAll: string;
    getTransacDate: string;
    getTransacRec: string;
    getTransacId: string;
    getAllGroups: string;
    getMedicinesCountByGroup: string;
    getMedicinesByGroup: string;
    getGroupById: string;
    createGroup: string;
    deleteGroup: string;
    dashInvStat: string;
    dashRev: string;
    dashMedAv: string;
    dashMedShort: string;
    dashTotalMed: string;
    dashGroups: string;
    dashMedSold: string;
    dashInvGen: string;
    dashTotalCust: string;
    dashFreqBought: string;
}

export const endpoints: Endpoints = {
    login: `/api/auth/login`,
    me: `/api/auth/me`,
    logout: `/api/auth/logout`,
    getUsers: `/api/users`,
    getUserId: `/api/users/`,
    createUser: `/api/users`,
    updateUser: `/api/users/`,
    deleteUser: `/api/users/`,
    getMedAll: `/api/medicines`,
    getGroupedMedAll: `/api/medicines/grouped-by-name`,
    getMedExp: `/api/medicines/expiration`,
    getMedId: `/api/medicines/`,
    createMed: `/api/medicines/`,
    updateMed: `/api/medicines/`,
    deleteMed: `/api/medicines/`,
    createTransac: `/api/transactions`,
    getTransacAll: `/api/transactions`,
    getTransacDate: `/api/transactions/date`,
    getTransacRec: `/api/transactions/receipt/:receiptNumber`,
    getTransacId: `/api/transactions/`,
    getAllGroups: `/api/groups`,
    getMedicinesCountByGroup: `/api/groups/:id/medicines/count`,
    getMedicinesByGroup: `/api/medicines/group/:groupId`,
    getGroupById: `/api/groups/:id`,
    createGroup: `/api/groups`,
    deleteGroup: `/api/groups/:id`,
    dashInvStat: `/api/dashboard/inventory-status`,
    dashRev: `/api/dashboard/revenue`,
    dashMedAv: `/api/dashboard/medicines-available`,
    dashMedShort: `/api/dashboard/medicine-shortage`,
    dashTotalMed: `/api/dashboard/total-medicines`,
    dashGroups: `/api/dashboard/medicine-groups`,
    dashMedSold: `/api/dashboard/medicines-sold`,
    dashInvGen: `/api/dashboard/invoices-generated`,
    dashTotalCust: `/api/dashboard/total-customers`,
    dashFreqBought: `/api/dashboard/frequently-bought`,
} as const;